---

- name: check | "Check host architecture"
  assert:
    msg: "Host architecture must be x86_64"
    that:
      - ansible_architecture == 'x86_64'

- name: check | Gather ansible_default_ipv4 from all hosts
  setup:
    gather_subset: '!all,network'
    filter: "ansible_default_ipv4"
  delegate_to: "{{ delegate_host_to_gather_facts }}"
  delegate_facts: yes
  when: hostvars[delegate_host_to_gather_facts].ansible_default_ipv4 is not defined
  loop: "{{ groups['all']|default([]) }}"
  loop_control:
    loop_var: delegate_host_to_gather_facts
  run_once: yes
  connection: "{{ (delegate_host_to_gather_facts == 'localhost') | ternary('local', omit) }}"

- name: reset | Reset k3s
  shell: |
     {{ 'k3s-uninstall.sh' if is_k3s_master else 'k3s-agent-uninstall.sh' }}
  ignore_errors: yes
  when: k3s_reset | default(false)

- include_tasks: install.yml
  when: not k3s_reset | default(false)
